name: a5btool
description: A tool for Rock 5B running Linux
version: 1.2.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.2.1
  build_version: ^2.1.1
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  args: ^2.3.1
  process_run: ^0.12.3+2
